[toolchain]
channel  = "nightly"          # no_std + asm! требуют nightly
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets  = [
    "x86_64-unknown-none",
    "aarch64-unknown-none",
    "riscv64gc-unknown-none-elf",
]
