# Default target — меняй под свою платформу разработки
[build]
target = "x86_64-unknown-none"

# Linker scripts для каждой архитектуры
[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tkernel/src/arch/x86_64/linker.ld",
    "-C", "relocation-model=static",
]

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tkernel/src/arch/aarch64/linker.ld",
    "-C", "relocation-model=static",
]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tkernel/src/arch/riscv64/linker.ld",
    "-C", "relocation-model=static",
]
